language: python

python:
  - '3.9'

before_install:
  - python -m pip install --upgrade pip
  
install:
  - pip install -r requirements.txt

addons:
  postgresql: '12'
  apt:
      packages:
        - postgresql-12
env:
  global:
  - PGUSER=postgres
  - PGPORT=5432
  - PGHOST=localhost

before_install:
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1
- postgres --version

before_script:


  - wget https://chromedriver.storage.googleapis.com/83.0.4103.14/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis/build/NunoMars/lastProject/

  - export CHROME_BIN=chromium-browser

env:
  - DJANGO_SETTINGS_MODULE=siteVoyanceconfig.settings.travis

script:
  - psql -c 'create database sitevoyance;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test