language: python

python:
  - '3.9'

before_install:
  - python -m pip install --upgrade pip
  
install:
  - pip install -r requirements.txt

addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

before_install:
  - sudo sed -i -e 's/^#listen_addresses.*/listen_addresses = "*"/' /etc/postgresql/11/main/postgresql.conf
  - sudo sed -i -e 's/^port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo service postgresql restart 11

before_script:


  - wget https://chromedriver.storage.googleapis.com/83.0.4103.14/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis/build/NunoMars/lastProject/

  - export CHROME_BIN=chromium-browser

env:
  - DJANGO_SETTINGS_MODULE=siteVoyanceconfig.settings.travis

script:
  - psql -c 'create database sitevoyance;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test